name: "contributor-ci-action"
author: "Vanessa Sochat"
description: "Extract repository contribution metadata."

inputs:
  results_dir:
    description: "If doing an extraction, save results here. Defaults to .cci in $PWD"
    required: false

  extract:
    description: "Run this kind of extraction (e.g., repos or all)"
    required: false
    default: repos
 
  repos_yaml:
    description: "The repos.yaml file with organization metadata."
    required: true
    default: repos.yaml

runs:
  using: "docker"
  image: "docker/Dockerfile"

branding:
  icon: "link"
  color: "blue"
